name: Upload Docker Software to TIRA
on: 
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.webis.de
          username: ${{ secrets.TIRA_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.TIRA_DOCKER_REGISTRY_TOKEN }}
      -
        name: Set up Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      -
        name: Install required python packages
        run: |
          python -m pip install --upgrade pip
          pip install tira==0.0.100
      -
        name: Set environment variables
        env:
          TIRA_TASK_ID: workshop-on-open-web-search
          TIRA_VM_ID: marcel-gohsen
        run: |
          tira-run --export-submission-environment \
          	GITHUB_SHA=${{ github.sha }} \
          	TIRA_VM_ID=${{ env.TIRA_VM_ID }} \
          	TIRA_TASK_ID=${{ env.TIRA_TASK_ID }} \
          	TIRA_DOCKER_REGISTRY_TOKEN=${{ secrets.TIRA_DOCKER_REGISTRY_TOKEN }} \
          	TIRA_DOCKER_REGISTRY_USER=${{ secrets.TIRA_DOCKER_REGISTRY_USER }} \
          	TIRA_CLIENT_TOKEN=${{ secrets.TIRA_CLIENT_TOKEN }} \
          	TIRA_CLIENT_USER=${{ secrets.TIRA_CLIENT_USER }} \
          	TIRA_CODE_REPOSITORY_ID=${{ secrets.TIRA_CODE_REPOSITORY_ID }} \
          	TIRA_DOCKER_FILE=Dockerfile \
          	TIRA_DOCKER_PATH=/ \
          	>> $GITHUB_ENV
           echo "\nIMAGE_TAG=registry.webis.de/code-research/tira/tira-user-marcel-gohsen/query-entity-linking:1.0" >> $GITHUB_ENV
      - name: Build, test, and upload image
        run: |
          docker build -t ${{ env.IMAGE_TAG }} ${{ github.workspace }}/${{ inputs.dockerpath }}
          tira-run --input-directory src/test/resources/cw09-input/ --image ${{ env.IMAGE_TAG }} --push true
